---
title: "3-green"
author: "Antonio Alegría"
date: "12/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(readr,
               dplyr,
               tidyr,
               lubridate,
               forcats,
               sf,
               ggplot2,
               scales,
               tmaptools,
               patchwork,
               png,
               grid,
               ggspatial
               )

# Datasets
# https://datos.gob.ar/dataset/agroindustria-agricultura---estimaciones-agricolas/archivo/agroindustria_95d066e6-8a0f-4a80-b59d-6f28f88eacd5
# https://datos.gob.ar/dataset/jgm-servicio-normalizacion-datos-geograficos/archivo/jgm_8.26

  datos_agricultura <- readr::read_csv("estimaciones-agricolas-2020-08.csv",
                                     locale=locale(encoding="latin1")) %>% 
  filter(cultivo == "Yerba mate")

  departamentos_sf <- read_sf("resources/departamentos/departamentos.shp")

    
  departamentos_prod_Yerba <- rmapshaper::ms_simplify(departamentos_sf, 
                                                       keep = 0.01) %>% 
    filter(IN1 %in% c(18056,18084,18147,18168,54119,54007,54014,54021,54028,
                      54035,54042,54049,54056,54063,54070,54077,54084,54091,
                      54098,54105,54112))

  
  # Integrar nombres correctos de departamentos al dataset de departamentos_sf


  departamentos_completo_sf <- departamentos_prod_Yerba %>% 
    mutate(departamento = case_when(NAM == "General Alvear" ~ "General Alvear", 
                                    NAM == "Ituzaingó" ~ "Ituzaingo",
                                    NAM == "Santo Tomé" ~ "Santo Tome",
                                    NAM == "San Martín" ~ "San Martin",
                                    NAM ==  "25de Mayo" ~ "25 de Mayo",
                                    NAM == "Apóstoles"  ~ "Apostoles" ,
                                    NAM == "Cainguás"  ~ "Cainguas" , 
                                    NAM == "Candelaria"  ~ "Candelaria" ,  
                                    NAM == "Capital"  ~ "Capital" ,  
                                    NAM == "Concepción"  ~ "Concepcion" ,  
                                    NAM == "Eldorado"  ~ "Eldorado" , 
                                    NAM == "General Manuel Belgrano"  ~ "General Manuel Belgrano" , 
                                    NAM == "Guaraní"  ~ "Guarani" , 
                                    NAM == "Iguazú"  ~ "Iguazu" , 
                                    NAM == "Leandro N. Alem"  ~ "Leandro N. Alem" , 
                                    NAM == "Libertador General San Martín"  ~ "Libertador General San Martin" , 
                                    NAM == "Montecarlo"  ~ "Montecarlo" , 
                                    NAM == "Oberá"  ~ "Obera" , 
                                    NAM == "San Ignacio"  ~ "San Ignacio" , 
                                    NAM == "San Javier"  ~ "San Javier",
                                    NAM == "San Pedro"  ~ "San Pedro"))
                                    

  provincias_sf <- read_sf("resources/provincias/provincias.shp")

  provincias_sf_simplyfy <- rmapshaper::ms_simplify(provincias_sf, 
                                                     keep = 0.01) %>% 
    filter(FNA != "Provincia de Tierra del Fuego, Antártida e Islas del Atlántico Sur")
  
  
```

## Data Wraaaaaaaaangling 

```{r echo=FALSE}

# Joined datasets: Producción y sf... By departamento ¿?
 dataset_joined <- left_join(departamentos_completo_sf, 
                              datos_agricultura, by = "departamento")

# Sumatoria de la producción desde 1969-2019
  dataset_suma_produccion_total <- datos_agricultura %>% 
    group_by(departamento) %>% 
    summarise(suma_total_anual = sum(produccion)) 
  
# Note. When joining a sf object + a data.table   
# if you want to maintain sf properties, then use the sf object first
# the other way the sf object transforms into a data.table
  
  dataset_joined_suma_produccion <- left_join(departamentos_completo_sf, 
                                              dataset_suma_produccion_total,
                                              by = "departamento") %>% 
    filter(!FNA %in% c("Departamento San Martín", 
                       "Departamento General Alvear")) 
  
```

## Maping

```{r yerba-map,echo=FALSE, cache=TRUE}
provincias_centroid <- cbind(provincias_sf_simplyfy,
                             st_coordinates(st_centroid(provincias_sf_simplyfy)
                                            )
                             )


departamentos_centroid <- cbind(dataset_joined_suma_produccion,
                            st_coordinates(st_centroid(dataset_joined_suma_produccion)
                                               )
                                )

plot_map_1 <- dataset_joined_suma_produccion %>%
    ggplot()+
    geom_point(data = provincias_centroid, 
               aes(X, Y),
               colour = "grey30",
               alpha = .5)+
    geom_sf(data = provincias_sf_simplyfy, 
            fill = "grey100", 
            color = "grey90", alpha = 0.4)+
    geom_sf(aes(fill = suma_total_anual))+
    geom_text(data = provincias_centroid, 
              aes(X, Y, label = NAM),
              check_overlap = TRUE,
              colour = "grey60",
              vjust = 0, hjust = 1.8
              )+
  geom_text(data = departamentos_centroid, 
            aes(X, Y, label = departamento),
            check_overlap = TRUE,
            colour = "grey30",
            size = 1.3,
            vjust = 1.5, 
              )+
      annotation_scale(location = "tl", 
                       pad_y = unit(1.5, "cm"),
                       height = unit(0.15, "cm"),
                       bar_cols = c("grey", "white"), 
                       line_col = "#444444",
                       text_col = "#444444") +
  annotation_north_arrow(location = "tl",
                         # Use true north
                         height = unit(0.75, "cm"),
                         width = unit(0.75, "cm"),
                         style =  north_arrow_minimal(line_width = .5,
                                                      line_col = "#444444",
                                                      fill = "#444444",
                                                      text_col = "#444444",
                                                      text_family = "",
                                                      text_face = "plain",
                                                      text_size = 10)
                          )+
  geom_point(data = departamentos_centroid,
             aes(X, Y),
             colour = "grey30",
             alpha = .3,
             size = .5)+
    geom_point(data = provincias_centroid, 
               aes(X, Y),
               colour = "grey30",
               alpha = .4)+

 # annotation_custom(rasterGrob(img), 
 #                   xmin = -49, 
 #                   xmax = -52.8, 
 #                   ymin = -21.6, 
 #                   ymax = -25)+
    theme_void (base_size = 15, base_family = "Futura")+
    labs(title = "50 Years of Argentinian \nYerba Mate Production",
         subtitle = "Argentinian Yerba Mate it's a plant grown and processed in the provinces Misiones y Corrientes. The leaves can be \nsteeped in hot water to make a beverage known as mate. Brewed cold, it is used to make tereré. The flavor resembles \nan infusion of vegetables, herbs, and is reminiscent of some varieties of green tea. According to data from the \nDepartamento de Estimaciones Agricolas and Instituto de la Yerma Mate, between 1969 to 2019, Argentina \nproduced more than 20 million tonnes of yerba.",
         caption = "Datasets: datos.gob.ar & Insti.Nac.Yerba Mate
         Illustration: @mlvvirtual | María Laura Villanueva
       DataViz: antonioalegria.io | Twitter: @elmedicobrujo")+
scale_fill_gradient2(low = "white",#DE6560
                     mid = "#FBF7EF",
                     high="#6A994E",#A7C957
                     midpoint = 1089361, 
                     limits = c(100000,
                                3000000),
                     labels = comma_format(big.mark = ","),
                     name = "Million Tonnes of Yerba Mate:",
                     guide = guide_legend(direction = "horizontal",
                                          label.position="bottom",
                                          title.position = "top"))+
    theme (plot.title.position = "plot",
           plot.title = element_text(size = 50, 
                                      
                                     margin = margin(0,0,0,0, "cm")),
           plot.subtitle = element_text(size = 10, family = "Roboto Light",
                                        margin = margin(.4,0,5,0, "cm")),
           plot.caption = element_text(family = "Futura",
                                       size = 8),
           plot.caption.position = "plot",
           legend.title = element_text(family = "Futura", size = 11),
           legend.text = element_text(size = 9, hjust = 1),
           legend.position = c(.19, 1.2),
           legend.key.height = unit(.5,"cm"),
           legend.key.width = unit(2,"cm"), 
           plot.margin = margin(2,1,2,1, "cm"),
           plot.background = element_rect(fill = "#F2E8CF", colour = NA),
          # panel.background = element_rect (fill = "red"),
           text = element_text(colour = "#782B2D")
           )+
    coord_sf(xlim =c(-53,-60) ,ylim =c(-27,-32) ,clip = "off", expand = TRUE)  


```

## plot ranking

```{r plot-ranking, echo=FALSE, cache=TRUE}
theme_set(theme_minimal(base_family = "Futura"))
plot_ranking <- dataset_joined_suma_produccion %>% 
  ggplot(aes(fct_reorder(departamento, suma_total_anual),
             suma_total_anual))+
  geom_col(aes(fill = suma_total_anual), 
           show.legend = FALSE)+
  geom_text(aes(label = scales::comma(suma_total_anual)),
            hjust = 1, size = 1,
            colour = "grey30")+
  theme_minimal(base_size = 15)+
  coord_flip()+
  scale_fill_gradient2(low = "white",#DE6560
                     mid = "#FBF7EF",
                     high="#6A994E",#A7C957
                     midpoint = 1089361,
                    # midpoint = 1000000, 
                     limits = c(100000,
                                3000000)
                     )+
  scale_y_continuous(labels = comma_format(big.mark = ","),
                     breaks = c (0,
                                 1000000,
                                 2000000,
                                 3000000),
                     limits = c(0,3000000))+
  labs(title = "Departments Production Ranking",
       subtitle = "Since 1969 up to 2019",
       x = "",
       y = "Million Tonnes")+
  theme(plot.title.position = "plot",
        plot.subtitle = element_text(size = 12),
        panel.grid = element_blank(),
        axis.title.x = element_text(hjust = 1.1, size = 8),
        axis.text.y = element_text(size = 6.5),
        axis.text.x = element_text(size = 6),
        text = element_text(colour = "#782B2D")
        )

plot_ranking

```

## Plot Assembling 

```{r, cache=TRUE}
plot_assemble <- plot_map_1+inset_element(plot_ranking,
                         left = 0.5, 
                         bottom = 0, 
                         right = 1, 
                         top = 0.5) & theme(plot.background = element_rect(fill = "#F2E8CF", colour = NA))



ggsave("test_2.png",
       plot = plot_assemble,
       scale = 1, 
       width = 12, 
       height = 12)
```
